# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = { 
    "/" =
      { device = "/dev/disk/by-label/nixos";
        fsType = "ext4";
      };
    "/boot" =
      { device = "/dev/disk/by-label/EFI";
        fsType = "vfat";
      };
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  fileSystems."/windows" =
    { device = "/dev/disk/by-label/OS";
      fsType = "ntfs"; 
      options = [ "rw" "uid=thomas"];
    };

}
